/*
Generated by LwipMibCompiler
*/

#ifndef CO2SENSOR_MIB_H
#define CO2SENSOR_MIB_H CO2SENSOR_MIB_H

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "lwip/apps/snmp_core.h"

extern const struct snmp_mib co2sensormib;

#define CO2_PPM_MEASUREMENT 1
#define TEMPERATURE_MEASUREMENT 2
#define HUMIDITY_MEASUREMENT 3
#define BATTERY_VOLTAGE_MEASUREMENT 4
#define BATTERY_CURRENT_MEASUREMENT 5

extern int get_measurement(u32_t, u32_t);
extern void print_serial(char* message);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* LWIP_SNMP */
#endif /* CO2SENSOR_MIB_H */