/*
Generated by LwipMibCompiler
*/

#ifndef SENSOR_HUB_H
#define SENSOR_HUB_H SENSOR_HUB_H

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "lwip/apps/snmp_core.h"

extern const struct snmp_mib sensorhub_mib;

#define CO2_PPM_MEASUREMENT 1
#define TEMPERATURE_MEASUREMENT 2
#define HUMIDITY_MEASUREMENT 3
#define BATTERY_VOLTAGE_MEASUREMENT 4
#define BATTERY_CURRENT_MEASUREMENT 5

extern int get_measurement(u32_t, u32_t);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* LWIP_SNMP */
#endif /* SENSOR_HUB_H */
